name: "bluebell"
mode: "release"
port: 8084
version: "v0.0.1"
start_time: "2024-12-12"
machine_id: 1

auth:
  jwt_secret: "bluebell"
  jwt_expire: 7200

log:
  level: "info"
  filename: "web_app.log"
  max_size: 500
  max_age: 30
  max_backups: 7
mysql:
  host: mysql8019
  port: 3306
  dbname: "bluebell"
  user: "root"
  password: "Long5230413"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: redis507
  port: 6379
  password: ""
  db: 0
  pool_size: 100
